### ISSUE TITLE
Super Mario Kart SRAM not being detected when opening or closing the game

### ISSUE THREAD

**Issue by Michael-Prince-Sharpe** [libretro/bsnes-jg#4]
In Super Mario Kart it seems like the SRAM isn't being detected because when you achieve any cups or unlock 150cc etc. it should save the progress but once you achieve unlock anything, if you unload or quit bsnes-jg then when you load up SuperMario Kart again all the progress you made has gone. I'm unsure if this is related to SRAM using enhancement chips (DSP in this case, SA-1 is another example of this kind of chip).

I'd also like to say BSNES-JG is a great fork of BSNES and seems to be the definitive way to play SNES games, in my opinion.

**Comment by carmiker** [comment]
Thanks for the compliment. A lot of work was put into this fork.

Yes, there is a problem. ~~It could be a complicated one to fix, and it is related to the way libretro works with raw memory blocks. In this case we are emulating the DSP at a low level, where the SRAM data is big endian. As a workaround, you can turn off LLE coprocessor emulation for now. I have a less than ideal hack that will fix this for LLE, but I would prefer to come up with a more correct solution.~~

Edit: I was wrong, actually the fix was simple once I took another look at it. A nightly build should be available soon with the fix, please let me know if this fixes it for you.

**Comment by Michael-Prince-Sharpe** [comment]
Yeah, it's all working great, thanks very much Carmiker.
